"""End-to-end smoke check for the Qdrant + Mistral retrieval stack.

Usage (inside the activated venv):

    python scripts/smoke_rag.py            # uses .env credentials

Verifies: embedding connectivity, vector-store availability/fallback,
hybrid retrieval quality, and (when LLM enabled) grounded answer synthesis.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import os

os.environ["PARCELPILOT_TESTING"] = "0"  # enable live integrations for this run


def main() -> int:
    from parcelpilot.agent import ParcelPilotAgent
    from parcelpilot.llm_config import is_mistral_enabled

    print("Mistral chat enabled:", is_mistral_enabled())

    agent = ParcelPilotAgent(
        ROOT, user={"user_id": "bob", "role": "support", "account_ids": ["ACCT-001"]}
    )
    store = agent.documents.vector_store
    print("Qdrant mode:", store.mode, "| url:", bool(store.url), "| enabled:", store.enabled)
    if store.last_error:
        print("Qdrant fallback note:", store.last_error)

    query = "how do refunds work if we cancel early?"
    results = agent.documents.search_documents(query, top_k=3)
    print(f"\nHybrid search returned {len(results)} results for: {query!r}")
    for index, result in enumerate(results, start=1):
        print(
            f"  {index}. {result['title']} "
            f"(authority={result['authority_label']}, status={result['status']})"
        )

    response = agent.handle_message("What is the return policy?")
    print("\nAgent tool_used:", response.get("tool_used"))
    print("Answer generated by:", response.get("answer_generated_by", "deterministic templates"))
    print("\nSummary:\n", response.get("summary", "")[:600])
    return 0 if results else 1


if __name__ == "__main__":
    raise SystemExit(main())